name: this_time
description: A new Flutter project.



publish_to: 'none'













version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'







dependencies:
  flutter:
    sdk: flutter




  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.3
  flutter_native_splash: ^2.2.17
  get: ^4.6.5
  liquid_swipe: ^3.0.0
  smooth_page_indicator: ^1.0.0+2
  flutter_otp_text_field: ^1.1.1
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter






  flutter_lints: ^2.0.1

flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/images/books.png
  image_dark: assets/images/books.png

android_12:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/images/books.png
  image_dark: assets/images/books.png





flutter:





  uses-material-design: true















  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/images/
    - assets/images/on_boarding_images/
    - assets/images/welcome_images/
    - assets/logo/
    - assets/images/forgot_password/
    - assets/images/dashboard/

