// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9YwWMxv76naj03PC0XBVBc4wPXAffWj8',
    appId: '1:585789590599:web:473b15c3e6678b62fc3562',
    messagingSenderId: '585789590599',
    projectId: 'akhil-project-9e10f',
    authDomain: 'akhil-project-9e10f.firebaseapp.com',
    storageBucket: 'akhil-project-9e10f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdaW6Dm5ZWxiKMIAYItO8xyK6VtmL3mgM',
    appId: '1:585789590599:android:b0a8641c8ecc4b51fc3562',
    messagingSenderId: '585789590599',
    projectId: 'akhil-project-9e10f',
    storageBucket: 'akhil-project-9e10f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU_Q9rTSHL_bYjV-r3CxbeRp1iloAy_sE',
    appId: '1:585789590599:ios:282f958bca7556f4fc3562',
    messagingSenderId: '585789590599',
    projectId: 'akhil-project-9e10f',
    storageBucket: 'akhil-project-9e10f.appspot.com',
    androidClientId: '585789590599-0u6rpn2g16h9d6h5369us10ph8nb8j6b.apps.googleusercontent.com',
    iosClientId: '585789590599-atbkuv0658hl9v30b24c0n5bna28n0d8.apps.googleusercontent.com',
    iosBundleId: 'com.example.thisTime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU_Q9rTSHL_bYjV-r3CxbeRp1iloAy_sE',
    appId: '1:585789590599:ios:282f958bca7556f4fc3562',
    messagingSenderId: '585789590599',
    projectId: 'akhil-project-9e10f',
    storageBucket: 'akhil-project-9e10f.appspot.com',
    androidClientId: '585789590599-0u6rpn2g16h9d6h5369us10ph8nb8j6b.apps.googleusercontent.com',
    iosClientId: '585789590599-atbkuv0658hl9v30b24c0n5bna28n0d8.apps.googleusercontent.com',
    iosBundleId: 'com.example.thisTime',
  );
}
